package org.example.estudebackendspring.enums;

public enum AnalysisType {
    PREDICT_SUBJECT_GRADE,
    PREDICT_SEMESTER_PERFORMANCE,
    ANALYZE_TEST,
    LEARNING_FEEDBACK,
    LEARNING_RECOMMENDATION,
    PRACTICE_QUIZ,
    IMPROVEMENT_EVALUATION,
    FULL_LEARNING_LOOP
}
